#!/bin/zsh

export XDG_CONFIG_HOME=$HOME/.config
export DOTFILES=$HOME/workspace/dotfiles/

# Oh My Zsh {{{
# -------------
export ZSH=$HOME/.oh-my-zsh
# }}}

# Editor {{{
# ----------
export EDITOR="nvim"
export VISUAL="nvim"
# }}}

# Node.js and NPM {{{
# -------------------
export NVM_DIR=$HOME/.nvm
# }}}

# Path {{{
# --------
export PATH="$PATH:$HOME/.local/share/rqp/bin"  # 
export PATH="$PATH:$HOME/.rvm/bin"              # RVM
# }}}
