#!/bin/zsh

export XDG_CONFIG_HOME="$HOME/.config"
export DOTFILES="$HOME/workspace/dotfiles/"

# Oh My Zsh {{{
# -------------
export ZSH="$HOME/.oh-my-zsh"
# }}}

# Editor {{{
# ----------
export EDITOR="emacs"
export VISUAL="emacs"
# }}}

# Node.js and NPM {{{
# -------------------
export NVM_DIR="$HOME/.nvm"
# }}}

# Path {{{
# --------
export PATH="$HOME/.local/share/rqp/bin:$PATH"     # RQP
export PATH="$HOME/.rvm/bin:$PATH"                 # RVM
export PATH="/usr/local/sbin:$PATH"                # sbin (for homebrew casks)
export PATH="$HOME/.emacs.d/bin:$PATH"             # doom
export PATH="$HOME/go/bin:$PATH"                   # go
export PATH="$HOME/bin:$PATH"                      # user binaries
export PATH="/opt/metasploit-framework/bin/:$PATH" # metasploit
export PATH="/usr/local/opt/openjdk/bin:$PATH"     # openjdk
export PATH="/usr/local/opt/libxml2/bin:$PATH"     # libxml2
# }}}

# libxml2 {{{
# -----------
export LDFLAGS="-L/usr/local/opt/libxml2/lib"
export CPPFLAGS="-I/usr/local/opt/libxml2/include"
export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"
# }}}
