#!/bin/zsh

export DOTFILES="$HOME/workspace/dotfiles/"

# Editor
export EDITOR="nvim"
export VISUAL="nvim"

# Node
export NVM_DIR="$HOME/.nvm"

# Rust
source "$HOME/.cargo/env"

# Path
export PATH="$HOME/.local/share/rqp/bin:$PATH"     # RQP
export PATH="/usr/local/sbin:$PATH"                # sbin (for homebrew casks)
export PATH="$HOME/.emacs.d/bin:$PATH"             # doom
export PATH="$HOME/bin:$PATH"                      # user binaries
